version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"

  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Welcome@123
      MYSQL_DATABASE: video-conference-app
